[project]
name = "s3uv1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "t-faugue-ece", email = "titouan.faugue@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.37.0",
]

[project.scripts]
dataset-users = "S3UV1.dataset_users:main"
dataset-orders = "S3UV1.dataset_orders:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
